### ISSUE TITLE
Add the ability to use a list of file objects (not just a file DOM element)

### ISSUE THREAD

**Issue by jasonmunro** [rico345100/socket.io-file-client#1]
Hello!
Thanks for putting this project together. For my needs I would like to have a way to send an array of file objects to the upload method, instead of just the file DOM element. This is useful when using some React components that don't expose the file DOM element. Would you be open to a pull request to add a new method to support this (or to modify the upload method to support both)?

Thanks again

**Comment by rico345100** [comment]
@jasonmunro Thank you for your suggestion. I just updated code to support FileList objects, so you can now pass the FileList directly. Make sure to update to v2.0.1. Thanks!
