### ISSUE TITLE
Large uploads

### ISSUE THREAD

**Issue by CloakedAlien** [rico345100/socket.io-file-client#3]
It would seem like the client has issues with really large uploads (3-4GB). Probably because the FileReader call is attempting to load the entire file into memory at once =)

Currently looking into a nodejs + js solution to handle >4GB uploads to avoid having to rely on HTTP limitations.

Most large upload (chunked uploads) libraries are cumbersome or outright buggy, I love the simplicity of effectiveness of this so far so it would seem that it's the only thing missing =)

**Comment by CloakedAlien** [comment]
I did a quick and dirty test, which seems to work fine, but it really needs a second pair of eyes to determine if it has any issues.

It has only had a few tests with large files but I haven't sanity-checked the logic or put it through more exhaustive scenarios.

It reads the file in chunks the size that are specified and sends the entire chunk at once (to avoid extra complexity).


```
// note that this function invoked from call/apply, which has "this" binded
function _upload(file, options) {
	options = options || {};

	var self = this;
	var socket = this.socket;
	var chunkSize = this.chunkSize;
	var transmissionDelay = this.transmissionDelay;
	var uploadId = file.uploadId;
	var uploadTo = options.uploadTo || '';
	var fileInfo = {
		id: uploadId,
		name: file.name,
		size: file.size,
		chunkSize: chunkSize,
		sent: 0,
		read: 0
	};

	uploadTo && (fileInfo.uploadTo = uploadTo);

	// check file mime type if exists
	if (self.accepts && self.accepts.length > 0) {
		var found = false;

		for (var i = 0; i < self.accepts.length; i++) {
			var accept = self.accepts[i];

			if (file.type === accept) {
				found = true;
				break;
			}
		}

		if (!found) {
			return self.emit('error', new Error('Not Acceptable file type ' + file.type + ' of ' + file.name + '. Type must be one of these: ' + self.accepts.join(', ')));
		}
	}

	// check file size
	if (self.maxFileSize && self.maxFileSize > 0) {
		if (file.size > +self.maxFileSize) {
			return self.emit('error', new Error('Max Uploading File size must be under ' + self.maxFileSize + ' byte(s).'));
		}
	}

	// put into uploadingFiles list
	self.uploadingFiles[uploadId] = fileInfo;

	// request the server to make a file
	self.emit('start', {
		name: fileInfo.name,
		size: fileInfo.size,
		uploadTo: uploadTo
	});
	socket.emit('socket.io-file::createFile', fileInfo);

	// read file
	var fileReader = new FileReader();
	fileReader.onloadend = function () {
		var buffer = fileReader.result;
		fileInfo.read += buffer.byteLength;

		if (fileInfo.aborted) {
			return;
		}

		self.emit('stream', {
			name: fileInfo.name,
			size: fileInfo.size,
			sent: fileInfo.sent,
			uploadTo: uploadTo
		});
		socket.once('socket.io-file::request::' + uploadId, nextChunk);
		socket.emit('socket.io-file::stream::' + uploadId, buffer);

		fileInfo.sent += buffer.byteLength;
		self.uploadingFiles[uploadId] = fileInfo;
	};

	function nextChunk() {
		if (fileInfo.sent >= fileInfo.size) {
			socket.emit('socket.io-file::done::' + uploadId);
			return;
		}
		if (fileInfo.read < fileInfo.size) {
			var slice = file.slice(fileInfo.read, fileInfo.read + fileInfo.chunkSize);
			fileReader.readAsArrayBuffer(slice);
		} else {
			console.log('Upload complete ' + fileInfo.read + ' - ' + fileInfo.size);
		}
	}

	socket.once('socket.io-file::request::' + uploadId, nextChunk);
	socket.on('socket.io-file::complete::' + uploadId, function (info) {
		self.emit('complete', info);

		socket.removeAllListeners('socket.io-file::abort::' + uploadId);
		socket.removeAllListeners('socket.io-file::error::' + uploadId);
		socket.removeAllListeners('socket.io-file::complete::' + uploadId);

		// remove from uploadingFiles list
		delete self.uploadingFiles[uploadId];
	});
	socket.on('socket.io-file::abort::' + uploadId, function (info) {
		fileInfo.aborted = true;
		self.emit('abort', {
			name: fileInfo.name,
			size: fileInfo.size,
			sent: fileInfo.sent,
			wrote: info.wrote,
			uploadTo: uploadTo
		});
	});
	socket.on('socket.io-file::error::' + uploadId, function (err) {
		self.emit('error', new Error(err.message));
	});
}
```

**Comment by rico345100** [comment]
Your code looks better than me, nice job!

I didn't thought that someone trying to upload huge binary files, so I needed some tests. If your code works fine, it would be great to merge your code.

**Comment by CloakedAlien** [comment]
Thank you! =)

I'm not very well versed with github but I could possibly work up a better implementation and do a pull request if that's preferable. This transfer method could always be made optional using settings, rather than straight up replacing the current one.

**Comment by rico345100** [comment]
@CloakedAlien That sounds great! What should I call your implementation? Any suggestion?

**Comment by ianbarker** [comment]
My resume PR #10 will also support large file uploads. That's why I wanted the resume functionality. I've tested with ~8GB files. @CloakedAlien I think it works pretty much the same way as your change, buffering and sending in chunks.

**Comment by rico345100** [comment]
Seems like this issue is now gone. I'm closing this, but you can re-open it if you have any issue!

**Comment by ghost** [comment]
Hey @rico345100 and @ianbarker!  I need a solution for uploading 1GB file by breaking into chunks and reasseble into db - not the filesystem at all.  Can I do this with your module?  Thannks
