### ISSUE TITLE
SocketIOFileClient ready-event only received once

### ISSUE THREAD

**Issue by blissi** [rico345100/socket.io-file-client#4]
Hallo,
given one instance of SocketIOFile, the ready-event is only received for the first SocketIOFileClient-instance that connects itself to the SocketIOFile.

That's because you're using
`socket.once('socket.io-file::reqSync', () => {`
instead of
`socket.on('socket.io-file::reqSync', () => {`

Could you fix this?

**Comment by rico345100** [comment]
Hi, @blissi .
Looks like this is socket.io-file issue, not the client module.
Anyway I will fix this soon, thank you for reporting!

**Comment by rico345100** [comment]
Fixed.
