### ISSUE TITLE
No info available. 

### ISSUE THREAD

**Issue by Subwater** [rico345100/socket.io-file-client#8]
There is no information available when I call `getUploadInfo()` it just returns an empty object.

**Comment by rico345100** [comment]
Hello, @Subwater . Can you describe more details? Also that could be happend if you upload the file before socket.io-file-client sync meta data with server. Try to upload after "ready" event triggered!

**Comment by rico345100** [comment]
Closing this because you didn't answer anymore. You can re-open this issue anytime if you needed.
